version: '3.7'

services:
  redis:
    container_name: redismod
    image: redislabs/redismod:latest
    ports:
      - 6380:6379/tcp

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=redis-app,grafana-piechart-panel,grafana-clock-panel
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-plugins:/var/lib/grafana/plugins
      - ./grafana-json-datasource:/var/lib/grafana/plugins/grafana-json-datasource
    user: "472:472"
